// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: msggameEnum.proto

package msggame

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 棋盘的旋转方式 逆时针 // 后端使用
type PCBRotation int32

const (
	PCBRotation_NoRotation  PCBRotation = 0
	PCBRotation_Rotation90  PCBRotation = 1
	PCBRotation_Rotation180 PCBRotation = 2
	PCBRotation_Rotation270 PCBRotation = 3
)

// Enum value maps for PCBRotation.
var (
	PCBRotation_name = map[int32]string{
		0: "NoRotation",
		1: "Rotation90",
		2: "Rotation180",
		3: "Rotation270",
	}
	PCBRotation_value = map[string]int32{
		"NoRotation":  0,
		"Rotation90":  1,
		"Rotation180": 2,
		"Rotation270": 3,
	}
)

func (x PCBRotation) Enum() *PCBRotation {
	p := new(PCBRotation)
	*p = x
	return p
}

func (x PCBRotation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PCBRotation) Descriptor() protoreflect.EnumDescriptor {
	return file_msggameEnum_proto_enumTypes[0].Descriptor()
}

func (PCBRotation) Type() protoreflect.EnumType {
	return &file_msggameEnum_proto_enumTypes[0]
}

func (x PCBRotation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PCBRotation.Descriptor instead.
func (PCBRotation) EnumDescriptor() ([]byte, []int) {
	return file_msggameEnum_proto_rawDescGZIP(), []int{0}
}

// 棋盘的翻转方式 // 后端使用
type PCBFlip int32

const (
	PCBFlip_NoFlip         PCBFlip = 0
	PCBFlip_FlipByVertical PCBFlip = 1
	PCBFlip_FlipByHorizon  PCBFlip = 2
)

// Enum value maps for PCBFlip.
var (
	PCBFlip_name = map[int32]string{
		0: "NoFlip",
		1: "FlipByVertical",
		2: "FlipByHorizon",
	}
	PCBFlip_value = map[string]int32{
		"NoFlip":         0,
		"FlipByVertical": 1,
		"FlipByHorizon":  2,
	}
)

func (x PCBFlip) Enum() *PCBFlip {
	p := new(PCBFlip)
	*p = x
	return p
}

func (x PCBFlip) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PCBFlip) Descriptor() protoreflect.EnumDescriptor {
	return file_msggameEnum_proto_enumTypes[1].Descriptor()
}

func (PCBFlip) Type() protoreflect.EnumType {
	return &file_msggameEnum_proto_enumTypes[1]
}

func (x PCBFlip) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PCBFlip.Descriptor instead.
func (PCBFlip) EnumDescriptor() ([]byte, []int) {
	return file_msggameEnum_proto_rawDescGZIP(), []int{1}
}

var File_msggameEnum_proto protoreflect.FileDescriptor

var file_msggameEnum_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x73, 0x67, 0x67, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x45, 0x54, 0x2a, 0x4f, 0x0a, 0x0b, 0x50, 0x43, 0x42, 0x52, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x6f, 0x52, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x39, 0x30, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x31, 0x38, 0x30, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x32, 0x37, 0x30, 0x10, 0x03, 0x2a, 0x3c, 0x0a, 0x07, 0x50, 0x43, 0x42, 0x46,
	0x6c, 0x69, 0x70, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x46, 0x6c, 0x69, 0x70, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x46, 0x6c, 0x69, 0x70, 0x42, 0x79, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x6c, 0x69, 0x70, 0x42, 0x79, 0x48, 0x6f, 0x72,
	0x69, 0x7a, 0x6f, 0x6e, 0x10, 0x02, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x6d, 0x73, 0x67, 0x67,
	0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msggameEnum_proto_rawDescOnce sync.Once
	file_msggameEnum_proto_rawDescData = file_msggameEnum_proto_rawDesc
)

func file_msggameEnum_proto_rawDescGZIP() []byte {
	file_msggameEnum_proto_rawDescOnce.Do(func() {
		file_msggameEnum_proto_rawDescData = protoimpl.X.CompressGZIP(file_msggameEnum_proto_rawDescData)
	})
	return file_msggameEnum_proto_rawDescData
}

var file_msggameEnum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_msggameEnum_proto_goTypes = []interface{}{
	(PCBRotation)(0), // 0: ET.PCBRotation
	(PCBFlip)(0),     // 1: ET.PCBFlip
}
var file_msggameEnum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msggameEnum_proto_init() }
func file_msggameEnum_proto_init() {
	if File_msggameEnum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msggameEnum_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msggameEnum_proto_goTypes,
		DependencyIndexes: file_msggameEnum_proto_depIdxs,
		EnumInfos:         file_msggameEnum_proto_enumTypes,
	}.Build()
	File_msggameEnum_proto = out.File
	file_msggameEnum_proto_rawDesc = nil
	file_msggameEnum_proto_goTypes = nil
	file_msggameEnum_proto_depIdxs = nil
}
